swiftmailer:
    transport:  '%env(MAILER_TRANSPORT)%'
    auth_mode:  '%env(MAILER_AUTHMODE)%'
    host:       '%env(MAILER_HOST)%'
    username:   '%env(MAILER_USERNAME)%'
    password:   '%env(MAILER_PASSWORD)%'
    port:       '%env(MAILER_PORT)%'
    spool:      { type: 'memory' }